### ISSUE TITLE
I can't seem to get this script to work

### ISSUE THREAD

**Issue by entreprenewer** [anaganisk/digitalocean-dynamic-dns-ip#13] opened 2021-05-18 14:52 UTC
Hi there
I'm not sure if anyone is around to actively help with this, but I've followed ALL the instructions, and when I run the script, this is what I get (IPs committed for privacy)

`umbrel@umbrel:~/digitalocean-dynamic-dns-ip $ ./digitalocean-dynamic-ip
2021/05/18 14:50:35 Discovered IPv4 address `xxx.226.170.xxx`
2021/05/18 14:50:36 Discovered IPv6 address `xxxx:ed0:4338:6e00:6988:8434:xxxx:26fd``

However, when I log in to my DigitalOcean, the record has not been updated accordingly. 
The API key is correct, I checked it twice.
Ideas? 

Thanks in advance.

**Comment by anaganisk** [comment] 2021-05-18 15:28
hi @entreprenewer have you created a DNS entry first? this script requires a DNS record to exist before it can start updating its IP (DO limitation)

**Comment by entreprenewer** [comment] 2021-05-18 15:52
WOW! Thanks SO much for the fast reply. I did create a DNS record, and changed it to something incorrect - it doesn't update to the correct one after running the script.

**Comment by anaganisk** [comment] 2021-05-18 16:16
@entreprenewer DO has a versioned API and this tool has been stable for a long time,  just to rule out API issues can you run the following commands. Check if the records are being updated properly.

```bash
#get your domain record
curl -X GET -H "Content-Type: application/json" -H "Authorization: Bearer yourtoken" "https://api.digitalocean.com/v2/domains/yourdomain.com/records" 

# get and use the record "id"  below
curl -X PUT -H "Content-Type: application/json" -H "Authorization: Bearer yourtoken" -d '{"data":"yourip"}' "https://api.digitalocean.com/v2/domains/example.com/records/recordid" 
```

**Comment by anaganisk** [comment] 2021-05-18 16:17
@entreprenewer also please do post your config, you can mask your data

**Comment by entreprenewer** [comment] 2021-05-19 16:19
Sorry for the delay.

For the first one, I get 
`{"id":"not_found","message":"Resource not found","request_id":"3b1f3cbb-6174-43d8-8192-e4b14f747109"}`

I didn't bother with the second b/c I don't have an ID.

Here's my config file:
`
{
  "apikey": "2cc0fd2bb2959c16exxxxxxxxxxx94559afaaxxxxx08195500axxx9c80dc3884d",
  "doPageSize": 20,
  "useIPv4": true,
  "useIPv6": true,
  "ipv4CheckUrl": "https://ipv4bot.whatismyipaddress.com",
  "ipv6CheckUrl": "https://ipv6bot.whatismyipaddress.com",
  "allowIPv4InIPv6": false,
  "domains": [
    {
      "domain": "domain.com",
      "records": [
        {
          "name": "pay",
          "type": "A"
        }
      ]
    }
  ]
}
`

**Comment by anaganisk** [comment] 2021-05-19 16:22
If there is an issue with the first url, there is something wrong either with your auth key or the curl request you made, are you sure u replaced all the placeholders I provided?
You can check the curl url and all placeholders
Also confirm if your auth key is valid for your DO account, you may try recreation.

**Comment by entreprenewer** [comment] 2021-05-19 16:25
Result of the first one:
`
vi.com/records"
{"domain_records":[{"id":79268116,"type":"SOA","name":"@","data":"1800","priority":null,"port":null,"ttl":1800,"weight":null,"flags":null,"tag":null},{"id":79268117,"type":"NS","name":"@","data":"ns1.digitalocean.com","priority":null,"port":null,"ttl":1800,"weight":null,"flags":null,"tag":null},{"id":79268118,"type":"NS","name":"@","data":"ns2.digitalocean.com","priority":null,"port":null,"ttl":1800,"weight":null,"flags":null,"tag":null},{"id":79268119,"type":"NS","name":"@","data":"ns3.digitalocean.com","priority":null,"port":null,"ttl":1800,"weight":null,"flags":null,"tag":null},{"id":79268242,"type":"A","name":"@","data":"165.227.188.11","priority":null,"port":null,"ttl":3600,"weight":null,"flags":null,"tag":null},{"id":79268250,"type":"CNAME","name":"www","data":"@","priority":null,"port":null,"ttl":43200,"weight":null,"flags":null,"tag":null},{"id":84411257,"type":"TXT","name":"@","data":"google-site-verification=zPOaxxxxxxxxxxvC-xUGxxxxxxxmdkI7zf4BiA","priority":null,"port":null,"ttl":3600,"weight":null,"flags":null,"tag":null},{"id":85064037,"type":"MX","name":"@","data":"aspmx.l.google.com","priority":1,"port":null,"ttl":14400,"weight":null,"flags":null,"tag":null},{"id":85064064,"type":"MX","name":"@","data":"alt1.aspmx.l.google.com","priority":5,"port":null,"ttl":14400,"weight":null,"flags":null,"tag":null},{"id":85064084,"type":"MX","name":"@","data":"alt2.aspmx.l.google.com","priority":5,"port":null,"ttl":14400,"weight":null,"flags":null,"tag":null},{"id":85064087,"type":"MX","name":"@","data":"aspmx2.googlemail.com","priority":10,"port":null,"ttl":14400,"weight":null,"flags":null,"tag":null},{"id":85064094,"type":"MX","name":"@","data":"aspmx3.googlemail.com","priority":10,"port":null,"ttl":14400,"weight":null,"flags":null,"tag":null},{"id":85735834,"type":"TXT","name":"iovo-16-12-2019._domainkey","data":"v=DKIM1; k=rsa; p=xxxxxxxxxxxxxxxxxBA1+K4Pn3nBWIyqC6mxxxxxxxxxceiUqVL7gFI8YHIQIDAQAB","priority":null,"port":null,"ttl":3600,"weight":null,"flags":null,"tag":null},{"id":85735844,"type":"TXT","name":"@","data":"v=spf1 include:_spf.google.com ~all","priority":null,"port":null,"ttl":3600,"weight":null,"flags":null,"tag":null},{"id":85735859,"type":"TXT","name":"@","data":"v=DMARC1; p=quarantine; pct=50;","priority":null,"port":null,"ttl":3600,"weight":null,"flags":null,"tag":null},{"id":150623399,"type":"A","name":"pay","data":"141.226.170.209","priority":null,"port":null,"ttl":3600,"weight":null,"flags":null,"tag":null}],"links":{},"meta":{"total":16}}
`


Second one:
`
{"domain_record":{"id":150623399,"type":"A","name":"pay","data":"xx1.226.162.xx","priority":null,"port":null,"ttl":3600,"weight":null,"flags":null,"tag":null}}
` 

That seems to have worked!!! Now, I wanna know why the script didn't work :)

**Comment by anaganisk** [comment] 2021-05-19 16:37
@entreprenewer  set useIPv6 to false in your config, you dont seem to have an AAAA record.

**Comment by entreprenewer** [comment] 2021-05-19 16:52
Did that, now when I run the script itself I'm getting:

`2021/05/19 16:51:24 Get https://ipv4bot.whatismyipaddress.com: dial tcp: lookup ipv4bot.whatismyipaddress.com on [2a02:ed0:6d6e:fd00::1]:53: read udp [2a02:ed0:6d6e:fd00:df86:d483:71bd:d32f]:32837->[2a02:ed0:6d6e:fd00::1]:53: i/o timeout`

I wonder if this is because I'm running TOR on other applications on this? It's a raspberry pi running Umbrel..

**Comment by johnjaylward** [comment] 2021-05-19 16:57
if you are running TOR on the rPI, I would expect that the exit node may end up as ipv4-only or ipv6-only ... with the current configuration we don't have a concept for an "optional" address type.

can you try running the script from a device that doesn't have TOR turned on and isn't routed through the rPI, or turn TOR off temporarily?

**Comment by entreprenewer** [comment] 2021-05-19 17:00
Hmm I guess I can try to install it on my Mac - I don't have another Linux device handy, and the RPI doesn't allow turning TOR off (Umbrel restriction).
What's odd, though, is that yesterday it WAS spitting out the IP address - just not updating DigitalOcean with it...?

**Comment by entreprenewer** [comment] 2021-05-19 17:02
I _am_ able to ping whatismyipaddress.com - however, when I try to run it now, I get:
2021/05/19 17:00:53 Get https://ipv4bot.whatismyipaddress.com: dial tcp 66.171.248.178:443: connect: network is unreachable

**Comment by johnjaylward** [comment] 2021-05-19 17:07
> I don't have another Linux device handy

you should be able to run this on almost any OS. The release tag has builds for just about everything.

**Comment by johnjaylward** [comment] 2021-05-19 17:10
also, I am able to get to https://ipv4bot.whatismyipaddress.com, but not ping it:

```
Pinging ipv4bot.whatismyipaddress.com [66.171.248.178] with 32 bytes of data:
Request timed out.
```

My guess is that the difference is in network configuration / firewall policies than the program itself

**Comment by anaganisk** [comment] 2021-05-19 17:46
@entreprenewer from what i can understand from errors, the tor node is IPv6, disable IPv4 in config and create an AAAA record, and run the script with new params. But to give you a heads up if your exit nodes change your config will go obsolete as @johnjaylward mentioned since tor nodes may be ipv6 or ipv4. If its possible to limit to either or have both that should work.
Keeping in mind all of these, without port forwording over TOR im wondering what use it would have anyway, your requests will never arrive to your node? I suggest you to lookup setting up .onion address instead.

**Comment by entreprenewer** [comment] 2021-05-19 18:41
Actually, to your point, that's exactly what I'm trying to do. I'm working on setting up a reverse proxy so that I can use BitPay Server on this machine despite the fact that it's routing most of it's traffic through Tor.

However, between installing nginx and other things, I seem to have disabled the internet on the device, so I probably need to reinstall the Umbrel OS fresh...

**Comment by anaganisk** [comment] 2021-06-06 07:13
Closing since the issue is not related to this project, feel free to reopen if otherwise

**Closed by anaganisk** 2021-06-06 07:13 UTC
